version: "3.9"

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${APP_PORT}:8000
    volumes:
      - .:/app
  # postgres:
  #   image: postgres:15
  #   ports:
  #     - "${DB_PORT}:5432"
  #   environment:
  #     POSTGRES_DB: ${DB_DATABASE}
  #     POSTGRES_USER: ${DB_USERNAME}
  #     POSTGRES_PASSWORD: ${DB_PASSWORD}
  #     POSTGRES_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
  #   volumes:
  #     - pgsql_data:/var/lib/postgresql/data

  # mysql:
  #   image: mysql:8
  #   ports:
  #     - "${DB_PORT}:3306"
  #   environment:
  #     MYSQL_DATABASE: ${DB_DATABASE}
  #     MYSQL_USER: ${DB_USERNAME}
  #     MYSQL_PASSWORD: ${DB_PASSWORD}
  #     MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
  #   volumes:
  #     - mysql_data:/var/lib/mysql

  # volumes:
  #   mysql_data:
  #     driver: local
  #   pgsql_data:
  #     driver: local
